KPL/FK

JUSTITIA_INERTIAL_ORBIT Frames Kernel
=====================================================================

   This frame kernel defines the inertial-frozen JUSTITIA_INERTIAL_ORBIT frame as a
   PARAMETERIZED TWO-VECTOR frame (CLASS=5) using CONSTANT defining vectors.

   Although CLASS=5 frames are commonly time-dependent, this definition is
   time-invariant because both primary and secondary vectors are specified as
   CONSTANT and expressed in the J2000 frame.


Version and Date
-----------------------------------------------------------

   Version 1.0 -- 2026-01-29 -- Giovanni Fereoli


Implementation Notes
-----------------------------------------------------------

   This file is used by the SPICE system as follows: programs that make
   use of this frame kernel must load the kernel, normally during
   program initialization using FURNSH.


\begindata

   FRAME_JUSTITIA_INERTIAL_ORBIT             = 200002693
   FRAME_200002693_NAME          = 'JUSTITIA_INERTIAL_ORBIT'
   FRAME_200002693_CLASS         = 5
   FRAME_200002693_CLASS_ID      = 200002693
   FRAME_200002693_CENTER        = '0'
   FRAME_200002693_RELATIVE      = 'J2000'
   FRAME_200002693_DEF_STYLE     = 'PARAMETERIZED'
   FRAME_200002693_FAMILY        = 'TWO-VECTOR'

   FRAME_200002693_PRI_AXIS      = 'Z'
   FRAME_200002693_PRI_VECTOR_DEF= 'CONSTANT'
   FRAME_200002693_PRI_SPEC      = 'RECTANGULAR'
   FRAME_200002693_PRI_VECTOR    = (  3.75295028111338677e-02, -3.15431733808413828e-01,  9.48205862524255427e-01 )
   FRAME_200002693_PRI_FRAME     = 'J2000'

   FRAME_200002693_SEC_AXIS      = 'X'
   FRAME_200002693_SEC_VECTOR_DEF= 'CONSTANT'
   FRAME_200002693_SEC_SPEC      = 'RECTANGULAR'
   FRAME_200002693_SEC_VECTOR    = ( -8.23724469850015018e-01,  5.27436137458721421e-01,  2.08060372663648935e-01 )
   FRAME_200002693_SEC_FRAME     = 'J2000'

\begintext

---------------------------------------------------------------------
Generated by  : Giovanni Fereoli
Affiliation   : CU Boulder / ORCCA Laboratory
Script        : make_justitia_inertial_frames.py
Script ver    : 1.0
Generated (UTC): 2026-01-29T22:45:27Z
SPICE toolkit : CSPICE_N0067
Metakernel    : kernelsJustitia/kernels.tm
---------------------------------------------------------------------

JUSTITIA_INERTIAL_ORBIT (frozen TWO-VECTOR frame)

Purpose
   Provide an inertially fixed orbital-plane-aligned frame. This is defined from the
   osculating (instantaneous) orbit plane at the epoch and then frozen relative to J2000.

Definition at epoch t0 (state in J2000)
   Target = 20000269
   Center = SUN

   r, v  := state(TARGET w.r.t. CENTER) at t0 in J2000

   +Z := unit(r x v)                          (orbit normal)
   +X := unit( r - (r·Z) Z )                  (r projected into orbital plane)

   The frame is implemented as a TWO-VECTOR construction using CONSTANT vectors in J2000.

Epoch (construction time only; frame is timeless afterwards)
   ET  = 0.000000 seconds past J2000
   UTC = 2000-01-01T11:58:55.816

Notes
   - This is "orbit-fixed" only in the sense of using the orbit plane at t0.
     If a time-averaged plane is required, compute an averaged/fitted normal and
     regenerate this kernel.

