KPL/FK

JUSTITIA_INERTIAL_BODY Frames Kernel
=====================================================================

   This frame kernel defines the inertial-frozen JUSTITIA_INERTIAL_BODY frame as a
   PARAMETERIZED TWO-VECTOR frame (CLASS=5) using CONSTANT defining vectors.

   Although CLASS=5 frames are commonly time-dependent, this definition is
   time-invariant because both primary and secondary vectors are specified as
   CONSTANT and expressed in the J2000 frame.


Version and Date
-----------------------------------------------------------

   Version 1.0 -- 2026-01-29 -- Giovanni Fereoli


Implementation Notes
-----------------------------------------------------------

   This file is used by the SPICE system as follows: programs that make
   use of this frame kernel must load the kernel, normally during
   program initialization using FURNSH.


\begindata

   FRAME_JUSTITIA_INERTIAL_BODY             = 200002692
   FRAME_200002692_NAME          = 'JUSTITIA_INERTIAL_BODY'
   FRAME_200002692_CLASS         = 5
   FRAME_200002692_CLASS_ID      = 200002692
   FRAME_200002692_CENTER        = '0'
   FRAME_200002692_RELATIVE      = 'J2000'
   FRAME_200002692_DEF_STYLE     = 'PARAMETERIZED'
   FRAME_200002692_FAMILY        = 'TWO-VECTOR'

   FRAME_200002692_PRI_AXIS      = 'Z'
   FRAME_200002692_PRI_VECTOR_DEF= 'CONSTANT'
   FRAME_200002692_PRI_SPEC      = 'RECTANGULAR'
   FRAME_200002692_PRI_VECTOR    = (  4.57370112212018634e-02,  5.30134279096181049e-01, -8.46679261545789874e-01 )
   FRAME_200002692_PRI_FRAME     = 'J2000'

   FRAME_200002692_SEC_AXIS      = 'X'
   FRAME_200002692_SEC_VECTOR_DEF= 'CONSTANT'
   FRAME_200002692_SEC_SPEC      = 'RECTANGULAR'
   FRAME_200002692_SEC_VECTOR    = ( -7.69460685074240591e-01, -5.21815442026851040e-01, -3.68291866034810067e-01 )
   FRAME_200002692_SEC_FRAME     = 'J2000'

\begintext

---------------------------------------------------------------------
Generated by  : Giovanni Fereoli
Affiliation   : CU Boulder / ORCCA Laboratory
Script        : make_justitia_inertial_frames.py
Script ver    : 1.0
Generated (UTC): 2026-01-29T22:45:27Z
SPICE toolkit : CSPICE_N0067
Metakernel    : kernelsJustitia/kernels.tm
---------------------------------------------------------------------

JUSTITIA_INERTIAL_BODY (frozen TWO-VECTOR frame)

Purpose
   Provide a non-rotating ("inertial-frozen") version of the rotating body-fixed
   frame JUSTITIA_BODY. This is intended for analyses/estimation where an
   inertially fixed body-aligned frame is preferred.

Definition
   The frame is defined by freezing the JUSTITIA_BODY axes at the epoch t0
   and expressing them as CONSTANT vectors in J2000:

      +Z := (JUSTITIA_BODY +Z) expressed in J2000 at t0
      +X := (JUSTITIA_BODY +X) expressed in J2000 at t0

   A TWO-VECTOR construction is used with:
      Primary axis   : Z defined by the constant +Z vector
      Secondary axis : X defined by the constant +X vector (projected as needed)

Epoch (construction time only; frame is timeless afterwards)
   ET  = 0.000000 seconds past J2000
   UTC = 2000-01-01T11:58:55.816

Properties
   - At the epoch, axes match JUSTITIA_BODY.
   - For all times, frame remains fixed relative to J2000 (no body spin).

