"""
Generate inertial-frozen Justitia frames as constant TWO-VECTOR (CLASS=5) frames.

Frames generated:
  1) JUSTITIA_INERTIAL_BODY
     - +Z aligned with JUSTITIA_BODY at epoch t0
     - +X aligned with JUSTITIA_BODY at epoch t0
     - inertially fixed for all times (vectors are CONSTANT in J2000)

  2) JUSTITIA_INERTIAL_ORBIT
     - +Z = orbit normal (r x v) at epoch t0
     - +X = r projected into orbital plane at epoch t0
     - inertially fixed for all times (vectors are CONSTANT in J2000)
"""

import numpy as np
import spiceypy as sp
from pathlib import Path
from datetime import datetime, timezone


# ---------------------------------------------------------------------
# Kernel loading
# ---------------------------------------------------------------------
META_KERNEL = "kernelsJustitia/kernels.tm"

# ---------------------------------------------------------------------
# Epoch definition
# If both are set, EPOCH_ET takes precedence.
# ---------------------------------------------------------------------
EPOCH_ET = 0.0  # seconds past J2000 (0.0 = J2000)
EPOCH_UTC = "2034-06-13T12:00:00"

# ---------------------------------------------------------------------
# Existing rotating body frame
# ---------------------------------------------------------------------
JUSTITIA_BODY_FRAME = "JUSTITIA_BODY"

# ---------------------------------------------------------------------
# Target / center for orbital frame
# ---------------------------------------------------------------------
TARGET = "20000269"
CENTER = "SUN"

# ---------------------------------------------------------------------
# New frame names
# ---------------------------------------------------------------------
INERTIAL_BODY_FRAME_NAME = "JUSTITIA_INERTIAL_BODY"
INERTIAL_ORBIT_FRAME_NAME = "JUSTITIA_INERTIAL_ORBIT"

# ---------------------------------------------------------------------
# Frame IDs (must be unique in your kernel set)
# ---------------------------------------------------------------------
INERTIAL_BODY_FRAME_ID = 200002692
INERTIAL_ORBIT_FRAME_ID = 200002693

# ---------------------------------------------------------------------
# Output files
# ---------------------------------------------------------------------
OUT_BODY_TF = Path("justitia_inertial_body.tf")
OUT_ORBIT_TF = Path("justitia_inertial_orbit.tf")

# ---------------------------------------------------------------------
# Provenance
# ---------------------------------------------------------------------
AUTHOR = "Giovanni Fereoli"
AFFILIATION = "CU Boulder / ORCCA Laboratory"
SCRIPT_NAME = "make_justitia_inertial_frames.py"
SCRIPT_VERSION = "1.0"


# ============================================================
# Utilities
# ============================================================


def unit(v: np.ndarray) -> np.ndarray:
    n = np.linalg.norm(v)
    if n <= 0.0:
        raise ValueError("Zero-norm vector encountered.")
    return v / n


def utc_now_stamp() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def spice_toolkit_version() -> str:
    try:
        return sp.tkvrsn("TOOLKIT")
    except Exception:
        return "UNKNOWN"


def et_to_utc(et: float) -> str:
    try:
        return sp.et2utc(et, "ISOC", 3)
    except Exception:
        return "UNKNOWN"


def fmt_vec(v: np.ndarray) -> str:
    # SPICE wants ( x, y, z )
    return f"( {v[0]: .17e}, {v[1]: .17e}, {v[2]: .17e} )"


def write_two_vector_frozen_frame(
    path: Path,
    frame_name: str,
    frame_id: int,
    center: str,
    relative: str,
    pri_axis: str,
    pri_vec_j2000: np.ndarray,
    sec_axis: str,
    sec_vec_j2000: np.ndarray,
    comment: str = "",
) -> None:
    """
    Write a CLASS=5 PARAMETERIZED TWO-VECTOR frame whose defining vectors are CONSTANT
    and expressed in the 'relative' frame (typically J2000). Such a frame is time-invariant.
    """

    gen_time = utc_now_stamp()
    toolkit = spice_toolkit_version()

    prov = f"""---------------------------------------------------------------------
Generated by  : {AUTHOR}
Affiliation   : {AFFILIATION}
Script        : {SCRIPT_NAME}
Script ver    : {SCRIPT_VERSION}
Generated (UTC): {gen_time}
SPICE toolkit : {toolkit}
Metakernel    : {META_KERNEL}
---------------------------------------------------------------------"""

    # Normalize defensively: constant vectors should be unit to avoid scaling surprises
    pv = unit(np.array(pri_vec_j2000, dtype=float))
    sv = unit(np.array(sec_vec_j2000, dtype=float))

    text = f"""KPL/FK

{frame_name} Frames Kernel
=====================================================================

   This frame kernel defines the inertial-frozen {frame_name} frame as a
   PARAMETERIZED TWO-VECTOR frame (CLASS=5) using CONSTANT defining vectors.

   Although CLASS=5 frames are commonly time-dependent, this definition is
   time-invariant because both primary and secondary vectors are specified as
   CONSTANT and expressed in the {relative} frame.


Version and Date
-----------------------------------------------------------

   Version {SCRIPT_VERSION} -- {gen_time[0:10]} -- {AUTHOR}


Implementation Notes
-----------------------------------------------------------

   This file is used by the SPICE system as follows: programs that make
   use of this frame kernel must load the kernel, normally during
   program initialization using FURNSH.


\\begindata

   FRAME_{frame_name}             = {frame_id}
   FRAME_{frame_id}_NAME          = '{frame_name}'
   FRAME_{frame_id}_CLASS         = 5
   FRAME_{frame_id}_CLASS_ID      = {frame_id}
   FRAME_{frame_id}_CENTER        = '{center}'
   FRAME_{frame_id}_RELATIVE      = '{relative}'
   FRAME_{frame_id}_DEF_STYLE     = 'PARAMETERIZED'
   FRAME_{frame_id}_FAMILY        = 'TWO-VECTOR'

   FRAME_{frame_id}_PRI_AXIS      = '{pri_axis}'
   FRAME_{frame_id}_PRI_VECTOR_DEF= 'CONSTANT'
   FRAME_{frame_id}_PRI_SPEC      = 'RECTANGULAR'
   FRAME_{frame_id}_PRI_VECTOR    = {fmt_vec(pv)}
   FRAME_{frame_id}_PRI_FRAME     = '{relative}'

   FRAME_{frame_id}_SEC_AXIS      = '{sec_axis}'
   FRAME_{frame_id}_SEC_VECTOR_DEF= 'CONSTANT'
   FRAME_{frame_id}_SEC_SPEC      = 'RECTANGULAR'
   FRAME_{frame_id}_SEC_VECTOR    = {fmt_vec(sv)}
   FRAME_{frame_id}_SEC_FRAME     = '{relative}'

\\begintext

{prov}

{comment}
"""
    path.write_text(text)
    print(f"[WROTE] {path}")


# ============================================================
# Main
# ============================================================

sp.furnsh(META_KERNEL)

# Epoch handling
epoch_et = (
    float(EPOCH_ET)
    if "EPOCH_ET" in globals() and EPOCH_ET is not None
    else sp.str2et(EPOCH_UTC)
)
epoch_utc = et_to_utc(epoch_et)

# ---------------------------------------------------------
# (1) Inertial-frozen body frame (two-vector, constant)
# ---------------------------------------------------------
# Rotation from JUSTITIA_BODY -> J2000 at epoch
R_body = np.array(sp.pxform(JUSTITIA_BODY_FRAME, "J2000", epoch_et), dtype=float)

# Columns are JUSTITIA_BODY unit axes expressed in J2000
x_hat_body_j2000 = R_body[:, 0]
z_hat_body_j2000 = R_body[:, 2]

write_two_vector_frozen_frame(
    OUT_BODY_TF,
    INERTIAL_BODY_FRAME_NAME,
    INERTIAL_BODY_FRAME_ID,
    center="0",  # inertial frame origin (same as your TKFRAME choice)
    relative="J2000",
    pri_axis="Z",
    pri_vec_j2000=z_hat_body_j2000,
    sec_axis="X",
    sec_vec_j2000=x_hat_body_j2000,
    comment=f"""JUSTITIA_INERTIAL_BODY (frozen TWO-VECTOR frame)

Purpose
   Provide a non-rotating ("inertial-frozen") version of the rotating body-fixed
   frame {JUSTITIA_BODY_FRAME}. This is intended for analyses/estimation where an
   inertially fixed body-aligned frame is preferred.

Definition
   The frame is defined by freezing the {JUSTITIA_BODY_FRAME} axes at the epoch t0
   and expressing them as CONSTANT vectors in J2000:

      +Z := ({JUSTITIA_BODY_FRAME} +Z) expressed in J2000 at t0
      +X := ({JUSTITIA_BODY_FRAME} +X) expressed in J2000 at t0

   A TWO-VECTOR construction is used with:
      Primary axis   : Z defined by the constant +Z vector
      Secondary axis : X defined by the constant +X vector (projected as needed)

Epoch (construction time only; frame is timeless afterwards)
   ET  = {epoch_et:.6f} seconds past J2000
   UTC = {epoch_utc}

Properties
   - At the epoch, axes match {JUSTITIA_BODY_FRAME}.
   - For all times, frame remains fixed relative to J2000 (no body spin).
""",
)

# ---------------------------------------------------------
# (2) Inertial-frozen orbital frame (two-vector, constant)
# ---------------------------------------------------------
state, _ = sp.spkezr(TARGET, epoch_et, "J2000", "NONE", CENTER)
r = np.array(state[0:3], dtype=float)
v = np.array(state[3:6], dtype=float)

z_hat_orb_j2000 = unit(np.cross(r, v))
x_hat_orb_j2000 = unit(r - np.dot(r, z_hat_orb_j2000) * z_hat_orb_j2000)

write_two_vector_frozen_frame(
    OUT_ORBIT_TF,
    INERTIAL_ORBIT_FRAME_NAME,
    INERTIAL_ORBIT_FRAME_ID,
    center="0",
    relative="J2000",
    pri_axis="Z",
    pri_vec_j2000=z_hat_orb_j2000,
    sec_axis="X",
    sec_vec_j2000=x_hat_orb_j2000,
    comment=f"""JUSTITIA_INERTIAL_ORBIT (frozen TWO-VECTOR frame)

Purpose
   Provide an inertially fixed orbital-plane-aligned frame. This is defined from the
   osculating (instantaneous) orbit plane at the epoch and then frozen relative to J2000.

Definition at epoch t0 (state in J2000)
   Target = {TARGET}
   Center = {CENTER}

   r, v  := state(TARGET w.r.t. CENTER) at t0 in J2000

   +Z := unit(r x v)                          (orbit normal)
   +X := unit( r - (r·Z) Z )                  (r projected into orbital plane)

   The frame is implemented as a TWO-VECTOR construction using CONSTANT vectors in J2000.

Epoch (construction time only; frame is timeless afterwards)
   ET  = {epoch_et:.6f} seconds past J2000
   UTC = {epoch_utc}

Notes
   - This is "orbit-fixed" only in the sense of using the orbit plane at t0.
     If a time-averaged plane is required, compute an averaged/fitted normal and
     regenerate this kernel.
""",
)

# Test: verify frames are inertially fixed

sp.furnsh("justitia_inertial_body.tf")
sp.furnsh("justitia_inertial_orbit.tf")

t1 = sp.str2et("2000-01-01T12:00:00")
t2 = sp.str2et("2035-01-01T12:00:00")

R1 = sp.pxform("J2000", "JUSTITIA_INERTIAL_BODY", t1)
R2 = sp.pxform("J2000", "JUSTITIA_INERTIAL_BODY", t2)

print("||R1 - R2|| =", np.linalg.norm(R1 - R2))

R1 = sp.pxform("J2000", "JUSTITIA_INERTIAL_ORBIT", t1)
R2 = sp.pxform("J2000", "JUSTITIA_INERTIAL_ORBIT", t2)

print("||R1 - R2|| =", np.linalg.norm(R1 - R2))

sp.kclear()
